# Generated by Django 5.1.4 on 2025-01-07 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_note_body_note_name_note_reps_note_sets_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='Ex',
        ),
    ]
