version: '3.11'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://tomas:haslo@db:5432/potegadata  # Używamy konfiguracji z Docker
    command: bash -c "sleep 5 && python3 manage.py runserver 0.0.0.0:8000 && python3 manage.py makemigrations && python3 manage.py migrate"
    networks:
      - siec
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: sh -c "sleep 10 && npm start"
    networks:
      - siec
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: tomas
      POSTGRES_PASSWORD: haslo
      POSTGRES_DB: potegadata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - siec

volumes:
  postgres_data:
networks:
   siec:
      driver: bridge
